clean: true
output: docs
theme: fullwidth
objc: true
sdk: iphonesimulator
module: Opener
umbrella_header: Opener.h
framework_root: .theos/_/usr/lib
author: HASHBANG Productions
author_url: https://hbang.github.io/
github_url: https://github.com/hbang/libopener
root_url: https://hbang.github.io/libopener/
dash_url: https://hbang.github.io/libopener/docsets/Opener.xml
readme: README.md
# documentation: info/*.md
exclude: "*/include/*"
hide_documentation_coverage: true
